name: ML-CI-CD-Pipeline
on: [push]
jobs:
  train:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and run tests
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt
          python src/pipes/test.py

  publish:
    needs: train
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies and build documentation
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install ghp-import

          make -C docs clean
          
          cd src
          sphinx-apidoc -o ../docs .
          cd ..
          
          make -C docs html
          ghp-import -n -p -f docs/_build/html
